import 'package:flutter_tags_x/flutter_tags_x.dart';

List conditions = [
  Item(index: 1, title: 'Dry cough', active: false),
  Item(index: 2, title: 'Aching body', active: false),
  Item(index: 3, title: 'High temperature', active: false),
  Item(index: 4, title: 'Sore throat', active: false),
  Item(index: 5, title: 'Headache', active: false),
  Item(index: 6, title: 'Difficulty sleeping', active: false),
  Item(index: 7, title: 'Loss of appetite', active: false),
  Item(index: 8, title: 'Diarrhoea', active: false),
  Item(index: 9, title: 'Stomach cramps', active: false),
  Item(index: 10, title: 'Stress', active: false),
  Item(index: 11, title: 'Eyesight problems', active: false),
  Item(index: 12, title: 'Feeling bloated', active: false),
  Item(index: 13, title: 'Cannot poo', active: false),
  Item(index: 14, title: 'Vomiting', active: false),
  Item(index: 15, title: 'Farting a lot', active: false),
  Item(index: 16, title: 'Feeling sick', active: false),
  Item(index: 18, title: 'Cold sore', active: false),
  Item(index: 19, title: 'Feeling full', active: false),
  Item(index: 20, title: 'Bloated after eating', active: false),
  Item(index: 21, title: 'Heartburn', active: false),
  Item(index: 22, title: 'Ear pain', active: false),
  Item(index: 23, title: 'Watery poo', active: false),
];